### ISSUE TITLE
uninitialized constant ApolloUploadServer::Rails on Heroku

### ISSUE THREAD

**Issue by gabceb** [jetruby/apollo_upload_server-ruby#18]
I get the following error when trying to initialize the console on Heroku

```
Running console on ⬢ REMOVED... up, run.3428 (Hobby)
Traceback (most recent call last):
	7: from /app/vendor/bundle/bin/console:29:in `<main>'
	6: from /app/vendor/bundle/bin/console:29:in `load'
	5: from /app/vendor/bundle/ruby/2.6.0/gems/apollo_upload_server-2.0.0.beta.3/bin/console:4:in `<top (required)>'
	4: from /app/vendor/bundle/ruby/2.6.0/gems/apollo_upload_server-2.0.0.beta.3/bin/console:4:in `require'
	3: from /app/vendor/bundle/ruby/2.6.0/gems/apollo_upload_server-2.0.0.beta.3/lib/apollo_upload_server.rb:4:in `<top (required)>'
	2: from /app/vendor/bundle/ruby/2.6.0/gems/apollo_upload_server-2.0.0.beta.3/lib/apollo_upload_server.rb:4:in `require'
	1: from /app/vendor/bundle/ruby/2.6.0/gems/apollo_upload_server-2.0.0.beta.3/lib/apollo_upload_server/railtie.rb:3:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/apollo_upload_server-2.0.0.beta.3/lib/apollo_upload_server/railtie.rb:4:in `<module:ApolloUploadServer>': uninitialized constant ApolloUploadServer::Rails (NameError)
```

Unfortunately, I can reproduce it locally 😢 

This is running Rails 6 on the [Heroku 18 stack](https://devcenter.heroku.com/articles/heroku-18-stack)

**Comment by gabceb** [comment]
Looks like running `rails c` via `heroku run` actually works so closing this one up!
